name: MockCommerce CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Use Node.Js Version 18
        uses: actions/setup-node@v2
        with: 
          node-version: "18"
      - run: npm run postinstall
      - run: npm run postbuild
